<?xml version="1.0" encoding="utf-8"?>
<kenticocommunity.qandaanswerdata>
  <QAndAAnswerDataAuthorMemberID>
    <GUID>f69d9d84-4ca9-4a3d-80f0-cff18438940a</GUID>
    <ObjectType>cms.member</ObjectType>
  </QAndAAnswerDataAuthorMemberID>
  <QAndAAnswerDataCodeName>-jlindsay-bluemodus-I-don-t-think-this-is-71afafa0</QAndAAnswerDataCodeName>
  <QAndAAnswerDataContent>
<![CDATA[
@jlindsay-bluemodus

I don't think this is possible. The exception is being caught by the platform at such a high/general level - the code displaying the toast doesn't know the cause or context of the error.

If you are building a custom module UI then I'd do the validation at the point that the data is being modified. You'll have some [page command](https://docs.kentico.com/x/4ASiCQ) or [page event lifecycle method](https://docs.kentico.com/developers-and-admins/customization/extend-the-administration-interface/ui-pages/ui-pages-with-forms#data-processing) that can catch the exception thrown by the event handler and return a more helpful message.

Worst case, you can provide a lot of helpful formatted details in the Event Log error message to guide the user to help resolve the problem.
]]>
  </QAndAAnswerDataContent>
  <QAndAAnswerDataDateCreated>2024-03-25 22:01:59Z</QAndAAnswerDataDateCreated>
  <QAndAAnswerDataGUID>05638462-4e68-44ca-88c2-216c04f3c809</QAndAAnswerDataGUID>
  <QAndAAnswerDataQuestionWebPageItemID>
    <CodeName>Event-handler-provide-custom-error-messag-ed1ed0bb</CodeName>
    <GUID>51d14bd5-0ae8-46a0-a1d0-6efdb9940bd0</GUID>
    <ObjectType>cms.webpageitem</ObjectType>
  </QAndAAnswerDataQuestionWebPageItemID>
  <QAndAAnswerDataWebsiteChannelID>
    <GUID>9ca57e0f-969f-43be-91d3-6c45659316bd</GUID>
    <ObjectType>cms.websitechannel</ObjectType>
    <Parent>
      <CodeName>devnet</CodeName>
      <GUID>4f636110-fd4a-4905-83e6-998752c2b2c2</GUID>
      <ObjectType>cms.channel</ObjectType>
    </Parent>
  </QAndAAnswerDataWebsiteChannelID>
</kenticocommunity.qandaanswerdata>